sudo: false

language: node_js
node_js:
  - '6'

install:
  - npm install -g elm@0.19.0 elm-test@0.19.0-beta4 elm-verify-examples@3.0.0

script:
  - rm -fr elm-stuff/generated-code/elm-explorations/test && elm-verify-examples
  - rm -fr elm-stuff/generated-code/elm-explorations/test && elm-test
